// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR77gIHvfcE87QB6rF7LMdxCJjRZ41-VU',
    appId: '1:378584748290:web:112d437a39bd795ac1b21b',
    messagingSenderId: '378584748290',
    projectId: 'main-time-fence',
    authDomain: 'main-time-fence.firebaseapp.com',
    storageBucket: 'main-time-fence.firebasestorage.app',
    measurementId: 'G-57Z69JXZEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBTz44f6OJEPQYc7Vw_WWuaGXyPAuwSQ',
    appId: '1:378584748290:android:82f8bdb08998af5bc1b21b',
    messagingSenderId: '378584748290',
    projectId: 'main-time-fence',
    storageBucket: 'main-time-fence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlTkZS_-qvqkuAs01rizHgDLREasFXO0',
    appId: '1:378584748290:ios:ba847791ae188f1ec1b21b',
    messagingSenderId: '378584748290',
    projectId: 'main-time-fence',
    storageBucket: 'main-time-fence.firebasestorage.app',
    iosBundleId: 'com.example.timeFence',
  );
}
